SELECT
    SQ.HID AS HID,
    SQ.NAME AS NAME,
    SUM(SQ.SCORE) AS SUM_SCORE
FROM
    (
    SELECT
        H.HACKER_ID AS HID,
        H.NAME AS NAME,
        S.CHALLENGE_ID,
        MAX(S.SCORE) AS SCORE
    FROM
        SUBMISSIONS AS S
    INNER JOIN HACKERS AS H
    ON S.HACKER_ID=H.HACKER_ID
    GROUP BY
        H.HACKER_ID,
        H.NAME,
        S.CHALLENGE_ID
    ) AS SQ
GROUP BY
    SQ.HID,
    SQ.NAME
HAVING
    SUM_SCORE > 0
ORDER BY
    SUM_SCORE DESC,
    HID
;