SELECT
    A.HACKER_ID AS HID,
    A.NAME AS NAME,
    SUM(B.MAX_SCORE) AS TOTAL
FROM
    HACKERS AS A
INNER JOIN
        (
        SELECT
            HACKER_ID AS HID,
            CHALLENGE_ID AS CID,
            MAX(SCORE) AS MAX_SCORE
        FROM
            SUBMISSIONS
        GROUP BY
            HID, CID
        ) AS B ON A.HACKER_ID=B.HID
GROUP BY
    HID, NAME
HAVING
    TOTAL>0
ORDER BY
    TOTAL DESC, HID
;