SELECT
    SQ.HID,
    SQ.NAME
FROM
    (
    SELECT
        H.HACKER_ID AS HID,
        H.NAME AS NAME,
        COUNT(S.CHALLENGE_ID) AS CNT
    FROM
        SUBMISSIONS AS S
    INNER JOIN HACKERS AS H ON S.HACKER_ID = H.HACKER_ID
    INNER JOIN CHALLENGES AS C ON S.CHALLENGE_ID = C.CHALLENGE_ID
    INNER JOIN DIFFICULTY AS D ON C.DIFFICULTY_LEVEL = D.DIFFICULTY_LEVEL
    WHERE
        S.SCORE = D.SCORE
    GROUP BY
        H.HACKER_ID,
        H.NAME
    ) AS SQ
WHERE
    SQ.CNT > 1
ORDER BY
    SQ.CNT DESC,
    SQ.HID
;