SELECT
    C.COMPANY_CODE AS CC,
    C.FOUNDER AS CF,
    COUNT(DISTINCT LM.LEAD_MANAGER_CODE) AS LM_CNT,
    COUNT(DISTINCT SM.SENIOR_MANAGER_CODE) AS SM_CNT,
    COUNT(DISTINCT M.MANAGER_CODE) AS M_CNT,
    COUNT(DISTINCT E.EMPLOYEE_CODE) AS E_CNT
FROM
    COMPANY AS C
INNER JOIN LEAD_MANAGER AS LM ON C.COMPANY_CODE=LM.COMPANY_CODE
INNER JOIN SENIOR_MANAGER AS SM ON LM.LEAD_MANAGER_CODE=SM.LEAD_MANAGER_CODE
INNER JOIN MANAGER AS M ON SM.SENIOR_MANAGER_CODE=M.SENIOR_MANAGER_CODE
INNER JOIN EMPLOYEE AS E ON M.MANAGER_CODE=E.MANAGER_CODE
GROUP BY
    C.COMPANY_CODE,
    C.FOUNDER
ORDER BY
    CC
;