SELECT
    CONCAT(NAME, '(', SUBSTR(OCCUPATION, 1, 1), ')') AS N
FROM
    OCCUPATIONS
ORDER BY
    NAME
;
SELECT
    CONCAT('There are a total of', ' ', COUNT(NAME), ' ', LOWER(OCCUPATION), 's.') AS N
FROM
    OCCUPATIONS
GROUP BY
    OCCUPATION
ORDER BY
    COUNT(NAME),
    OCCUPATION
;