SELECT
    A.CONTEST_ID,
    A.HACKER_ID,
    A.NAME,
    SUM(E.TS) AS SUM_TS,
    SUM(E.TAS) AS SUM_TAS,
    SUM(D.TV) AS SUM_TV,
    SUM(D.TUV) AS SUM_TUV
FROM
    CONTESTS AS A
LEFT JOIN COLLEGES AS B ON A.CONTEST_ID=B.CONTEST_ID
LEFT JOIN CHALLENGES AS C ON B.COLLEGE_ID=C.COLLEGE_ID
LEFT JOIN
        (
        SELECT
            CHALLENGE_ID,
            SUM(TOTAL_VIEWS) AS TV,
            SUM(TOTAL_UNIQUE_VIEWS) AS TUV
        FROM
            VIEW_STATS
        GROUP BY
            CHALLENGE_ID
        ) AS D ON C.CHALLENGE_ID=D.CHALLENGE_ID
LEFT JOIN
        (
        SELECT
            CHALLENGE_ID,
            SUM(TOTAL_SUBMISSIONS) AS TS,
            SUM(TOTAL_ACCEPTED_SUBMISSIONS) AS TAS
        FROM
            SUBMISSION_STATS
        GROUP BY
            CHALLENGE_ID
        ) AS E ON C.CHALLENGE_ID=E.CHALLENGE_ID
GROUP BY
    A.CONTEST_ID,
    A.HACKER_ID,
    A.NAME
HAVING
    SUM(D.TV)+SUM(D.TUV)+SUM(E.TS)+SUM(E.TAS)>0
;