SELECT
    A.NAME
FROM
    STUDENTS AS A
INNER JOIN FRIENDS AS B ON A.ID=B.ID
INNER JOIN PACKAGES AS P1 ON A.ID=P1.ID
INNER JOIN PACKAGES AS P2 ON B.FRIEND_ID=P2.ID
WHERE
    P1.SALARY<P2.SALARY
ORDER BY
    P2.SALARY
;