SELECT
    SQ1.SD AS SD,
    MIN(SQ2.ED) AS ED
FROM
    (
    SELECT
        A.START_DATE AS SD
    FROM
        PROJECTS AS A
    LEFT JOIN PROJECTS AS B
    ON A.START_DATE=B.END_DATE
    WHERE B.END_DATE IS NULL
    ) AS SQ1,
    (
    SELECT
        B.END_DATE AS ED
    FROM
        PROJECTS AS A
    RIGHT JOIN PROJECTS AS B
    ON A.START_DATE=B.END_DATE
    WHERE A.START_DATE IS NULL
    ) AS SQ2
WHERE
    SQ1.SD < SQ2.ED
GROUP BY
    SQ1.SD
ORDER BY
    DATEDIFF(MIN(SQ2.ED), SD),
    SD
;