SET @r1=0, @r2=0;

SELECT
	SQ1.X AS X,
	SQ1.Y AS Y
FROM
	(SELECT @r1:=@r1+1 AS RN, X, Y FROM FUNCTIONS ORDER BY X) AS SQ1,
	(SELECT @r2:=@r2+1 AS RN, X, Y FROM FUNCTIONS ORDER BY X) AS SQ2
WHERE
	SQ1.RN < SQ2.RN
	AND SQ1.X=SQ2.Y
	AND SQ1.Y=SQ2.X
ORDER BY
	X
;