SET @R1=0, @R2=0;
SELECT
    A.X,A.Y
FROM
    (SELECT @R1:=@R1+1 AS RN, X, Y FROM FUNCTIONS ORDER BY X) AS A,
    (SELECT @R2:=@R2+1 AS RN, X, Y FROM FUNCTIONS ORDER BY X) AS B
WHERE
    A.RN<B.RN
    AND A.X=B.Y
    AND A.Y=B.X
ORDER BY
    A.X
;